spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/artfolio
    username: artfolio
    password: artfolio
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
