spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/artfolio
    username: artfolio
    password: artfolio
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
spaces:
  endpoint: https://sfo3.digitaloceanspaces.com
  region: sfo3
  bucket: artfolio-assets
  access-key: ${SPACES_ACCESS_KEY}
  secret-key: ${SPACES_SECRET_KEY}
  
server:
  port: 8080
